AWSTemplateFormatVersion: "2010-09-09"
Description:

Parameters:
  PraefectLbSecurityGroupId:
    Description: Id of the PraefectLb Security Group
    Type: AWS::EC2::SecurityGroup::Id

  RailsLbSecurityGroupId:
    Description: Id of the RailsLb Security Group
    Type: AWS::EC2::SecurityGroup::Id

  LbSubnet1:
    Description: SubnetId for the ALB
    Type: AWS::EC2::Subnet::Id

  LbSubnet2:
    Description: SubnetId for the ALB
    Type: AWS::EC2::Subnet::Id

  VpcId:
    Description: VPC ID
    Type: String

Resources:
  PraefectLb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      SecurityGroups:
        - !Ref PraefectLbSecurityGroupId
      Subnets:
        - !Ref LbSubnet1
        - !Ref LbSubnet2

  RailsLb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      SecurityGroups:
        - !Ref RailsLbSecurityGroupId
      Subnets:
        - !Ref LbSubnet1
        - !Ref LbSubnet2

  PraefectTg:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      # HealthCheckEnabled: Boolean
      # HealthCheckIntervalSeconds: Integer
      # HealthCheckPath: String
      # HealthCheckPort: String
      # HealthCheckProtocol: String
      # HealthCheckTimeoutSeconds: Integer
      # HealthyThresholdCount: Integer
      # Matcher:
      #   Matcher
      Port: 2305
      Protocol: tcp
      TargetType: instance
      # UnhealthyThresholdCount: Integer
      VpcId: !Ref VpcId

  RailsTg:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      # HealthCheckEnabled: Boolean
      # HealthCheckIntervalSeconds: Integer
      # HealthCheckPath: String
      # HealthCheckPort: String
      # HealthCheckProtocol: String
      # HealthCheckTimeoutSeconds: Integer
      # HealthyThresholdCount: Integer
      # Matcher:
      #   Matcher
      Port: 80
      Protocol: tcp
      TargetType: instance
      # UnhealthyThresholdCount: Integer
      VpcId: !Ref VpcId

  PraefectListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref PraefectTg
          Type: forward
      LoadBalancerArn: !Ref PraefectLb
      Port: 2305
      Protocol: tcp

  RailsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref RailsTg
          Type: forward
      LoadBalancerArn: !Ref RailsLb
      Port: 80
      Protocol: tcp