AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  RailsLbSecurityGroupId:
    Description: Id of the RailsLb Security Group
    Type: AWS::EC2::SecurityGroup::Id

  PraefectLbSubnet1:
    Description: SubnetId for the ALB
    Type: AWS::EC2::Subnet::Id

  PraefectLbSubnet2:
    Description: SubnetId for the ALB
    Type: AWS::EC2::Subnet::Id

  RailsLbSubnet1:
    Description: SubnetId for the ALB
    Type: AWS::EC2::Subnet::Id

  RailsLbSubnet2:
    Description: SubnetId for the ALB
    Type: AWS::EC2::Subnet::Id

  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id

Resources:
  PraefectLb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: network
      Scheme: internal
      Subnets:
        - !Ref PraefectLbSubnet1
        - !Ref PraefectLbSubnet2

  RailsLb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      SecurityGroups:
        - !Ref RailsLbSecurityGroupId
      Subnets:
        - !Ref RailsLbSubnet1
        - !Ref RailsLbSubnet2

  PraefectTg:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      # HealthCheckEnabled: Boolean
      # HealthCheckIntervalSeconds: Integer
      # HealthCheckPath: String
      # HealthCheckPort: String
      # HealthCheckProtocol: String
      # HealthCheckTimeoutSeconds: Integer
      # HealthyThresholdCount: Integer
      # Matcher:
      #   Matcher
      Port: 2305
      Protocol: TCP
      TargetType: instance
      # UnhealthyThresholdCount: Integer
      VpcId: !Ref VpcId

  RailsTg:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      # HealthCheckEnabled: Boolean
      # HealthCheckIntervalSeconds: Integer
      # HealthCheckPath: String
      # HealthCheckPort: String
      # HealthCheckProtocol: String
      # HealthCheckTimeoutSeconds: Integer
      # HealthyThresholdCount: Integer
      # Matcher:
      #   Matcher
      Port: 80
      Protocol: HTTP
      TargetType: instance
      # UnhealthyThresholdCount: Integer
      VpcId: !Ref VpcId

  PraefectListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref PraefectTg
          Type: forward
      LoadBalancerArn: !Ref PraefectLb
      Port: 2305
      Protocol: TCP

  RailsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref RailsTg
          Type: forward
      LoadBalancerArn: !Ref RailsLb
      Port: 80
      Protocol: HTTP
