AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  BucketNamePrefix:
    Type: String

Resources:
  GitlabArtifacts:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BucketNamePrefix}-artifacts

  GitlabExternalDiffs:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BucketNamePrefix}-external-diffs

  GitlabLfs:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BucketNamePrefix}-lfs

  GitlabUploads:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BucketNamePrefix}-uploads

  GitlabPackages:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BucketNamePrefix}-packages

  GitlabDependencyProxy:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BucketNamePrefix}-dependency-proxy
